/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Kei' at '10/11/16 22:58' with Gradle 3.1
 *
 * @author Kei, @date 10/11/16 22:58
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
